[tool.poetry]
name = "bernard"
version = "0.4.1"
description = "Bot Engine Responding Naturally At Requests Detection"
authors = ["Rémy Sanchez <remy.sanchez@hyperthese.net>"]
license = "AGPL-3.0-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "^3.9.1"
redis = "^5.0.1"
ujson = "^5.9.0"
Unidecode = "^1.3.7"
PyJWT = "^2.8.0"
uvloop = "^0.19.0"
sentry-sdk = "^1.39.1"
Babel = "^2.14.0"
python-dateutil = "^2.8.2"
pytz = "^2022.6"
aionotify = "^0.2.0"
facepy = "^1.0.12"
google-api-python-client = "^2.111.0"
oauth2client = "^4.1.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
twine = "^4.0.2"
isort = "^5.13.2"
black = "^23.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
