name: Validation

on:
  push:
    branches:
      - develop
    tags:
      - '*'

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - &code
        name: Checkout code
        uses: actions/checkout@v3

      - &python
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3'

      - &cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - &dependencies
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt

      - &build
        name: Build package
        run: make build

      - name: Install package
        run: python -m pip install dist/*

      - name: Run Pytest
        run: python -m pytest

  pypi:
    name: Publish to Pypi
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    needs:
      - tests
    steps:
      - *code
      - *python
      - *cache
      - *dependencies
      - *build

      - name: Upload to Pypi
        run: python -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
