name: Validation
on: push
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install tools
        run: python -m pip install --upgrade pip wheel setuptools

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Build package
        run: make build

      - name: Install package
        run: python -m pip install dist/*

      - name: Run Pytest
        run: python -m pytest
